project:
  name: quickstart-nvidia-parabricks
  owner: quickstart-eng@amazon.com
  #marketplace-ami: true
  s3_regional_buckets: true
  regions:
    - ap-southeast-2
    - eu-west-1
    - us-east-1
    - us-west-2
  s3_bucket: ''
  template: templates/parabricks-main.template.yaml
tests:
  default:
    parameters:
      AvailabilityZones: "$[taskcat_genaz_2]"
      KeyPairName: "$[taskcat_getkeypair]"
      PrivateSubnet1ACIDR: "10.0.0.0/19"
      PrivateSubnet2CIDR: "10.0.32.0/19"
      PublicSubnet1CIDR: "10.0.128.0/20"
      PublicSubnet2CIDR: "10.0.144.0/20"
      VPCCIDR: "10.0.0.0/16"
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      ParabricksURI: override
    regions:
     #- eu-west-1
      #- us-east-1
      - us-west-2
      #- ap-southeast-2
