project:
  owner: gburnett@nvidia.com
  regions:
    - us-west-2
 
tests:
  quickstart-nvidia-parbaricks-test:
    parameters: batch-params.test.json
    template: parabricks-main-template.yaml
    regions:
      - us-west-2
